spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventrack
    username: postgres
    password: test1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
stripe:
  secretKey: sk_test_your_secret_key

paypal:
  client-id: your_paypal_client_id
  client-secret: your_paypal_client_secret
  mode: sandbox or live
server:
  port: 8000